name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Read current version from Cargo.toml
        id: version
        run: |
          version=$(grep '^version' Cargo.toml | head -n 1 | sed 's/version = "//' | sed 's/"//')
          echo "::set-output name=current_version::$version"
    
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USER }}/chrisbratti-website
    
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/chrisbratti-website:${{ steps.version.outputs.current_version }}
          labels: ${{ steps.meta.outputs.labels }}

  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          ref: master

      - name: Increment Version
        id: bump-version
        run: |
          current_version=$(grep '^version' Cargo.toml | head -n 1 | sed 's/version = "//' | sed 's/"//')
          echo "Current version: $current_version"

          new_version=$(echo "$current_version" | awk -F '[./]' '{ printf "%d.%d.%d\n", $1, $2, $3+1 }')
          echo "New version: $new_version"

          sed -i "s/^version = \".*\"/version = \"$new_version\"/" Cargo.toml

          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "[UpdateBot] Version bump to ${{ env.new_version }}"
          git push origin HEAD:master
